@ECHO OFF
TITLE Import SEP Regs - Suporte Nível 3 RJ - Sonda IT
::BATCH escrita por Diego Rosário Sousa
CHOICE /C SN /M "A BATCH ALTERA CHAVES DE REGISTRO, DESEJA REALMENTE CONTINUAR"
SET BATCHPATH = %~dp0
IF EXIST "%BATCHPATH%SEP_REG_BACKUP" (
	CD /D "%BATCHPATH%SEP_REG_BACKUP"
	FOR /F "DELIMS=" %%A IN ('DIR /S /B') DO REG IMPORT %%A
) ELSE (
	ECHO A BATCH PRECISA ESTAR NA MESMA PASTA "QUE SEP_REG_BACKUP"
)