@ECHO OFF
GOTO INICIO

::DECLARAÇÃO DAS FUNÇÕES

::NOME DA FUNÇÃO
:ECHO_PA

::AÇÕES DA FUNÇÃO
ECHO VOCÊ DIGITOU: %VAR%
ECHO.

::PONTO DE RETORNO (IMPORTANTE!)
GOTO %RETORNO%

::NOME DA SUB-ROTINA PRA ONDE A FUNÇÃO TEM QUE VOLTAR
:INICIO
SET /P VAR=DIGA:

::SEMPRE DEFINIR O RETORNO ANTES DE CHAMAR A FUNÇÃO
SET RETORNO=INICIO
CALL :ECHO_PA