# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from getpass import getpass
from gettext import gettext

email = gettext("e-mail")
password = getpass()


class TestLoggingin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loggingin(self):
    self.driver.get("https://accounts.highbond.com/login")
    self.driver.find_element(By.ID, "user_email").send_keys("diego.sousa@quality.com.br")
    self.driver.find_element(By.ID, "user_password").send_keys(password)
    self.driver.find_element(By.ID, "user_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Robôs").click()
    self.driver.find_element(By.LINK_TEXT, "PRD_V3").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(2) .dashboard__robot-list-item-button").click()
    self.driver.find_element(By.CLASS_NAME, "folder__robots")
    self.driver.find_element(By.CSS_SELECTOR, ".sc-bdVaJa").click()
    self.driver.current_url